from learning.models import GrammarUnit, LearningModule, PhraseUnit, VocabularyUnit

VOCABULARY_UNITS = [
    VocabularyUnit(
        id="vocab-aamu",
        level="A1",
        module_ids=["module-daily-life-routines"],
        finnish="aamu",
        english="morning",
        part_of_speech="noun",
        example="Aamu alkaa kahvilla ja rauhallisella hetkella.",
        related_unit_ids=["grammar-time-adverbs", "phrase-heraan-aamulla"],
    ),
    VocabularyUnit(
        id="vocab-ilta",
        level="A1",
        module_ids=["module-daily-life-routines"],
        finnish="ilta",
        english="evening",
        part_of_speech="noun",
        example="Illalla palaan kotiin ja teen ruokaa.",
        related_unit_ids=["grammar-time-adverbs", "phrase-minulla-on-iltavuoro"],
    ),
    VocabularyUnit(
        id="vocab-tyo",
        level="A1",
        module_ids=["module-daily-life-routines", "module-work-and-study-communication"],
        finnish="tyo",
        english="work",
        part_of_speech="noun",
        example="Tyo alkaa kello kahdeksan arkiaamuisin.",
        related_unit_ids=[
            "vocab-kokous",
            "vocab-vuoro",
            "phrase-minulla-on-iltavuoro",
            "phrase-voinko-siirtaa-kokousta",
        ],
    ),
    VocabularyUnit(
        id="vocab-asua",
        level="A1",
        module_ids=["module-daily-life-routines"],
        finnish="asua",
        english="to live",
        part_of_speech="verb",
        example="Asun pienessa asunnossa lahella keskustaa.",
        related_unit_ids=["grammar-verb-present", "phrase-asun-helsingissa"],
    ),
    VocabularyUnit(
        id="vocab-opiskella",
        level="A2",
        module_ids=["module-daily-life-routines", "module-work-and-study-communication"],
        finnish="opiskella",
        english="to study",
        part_of_speech="verb",
        example="Opiskelen suomea joka paiva tunnin ajan.",
        related_unit_ids=["grammar-verb-present", "grammar-conjunctions"],
    ),
    VocabularyUnit(
        id="vocab-asema",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="asema",
        english="station",
        part_of_speech="noun",
        example="Asema on torin vieressa.",
        related_unit_ids=[
            "vocab-vasen",
            "vocab-oikea",
            "grammar-local-cases",
            "phrase-missa-asema-on",
        ],
    ),
    VocabularyUnit(
        id="vocab-kirjasto",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="kirjasto",
        english="library",
        part_of_speech="noun",
        example="Kirjasto on rauhallinen paikka lukea ja opiskella.",
        related_unit_ids=[
            "grammar-local-cases",
            "grammar-question-forms",
            "phrase-kirjasto-on-lahella",
        ],
    ),
    VocabularyUnit(
        id="vocab-vasen",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="vasen",
        english="left",
        part_of_speech="adjective",
        example="Kaanny vasemmalle liikennevalojen kohdalta.",
        related_unit_ids=["vocab-oikea", "phrase-missa-asema-on"],
    ),
    VocabularyUnit(
        id="vocab-oikea",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="oikea",
        english="right",
        part_of_speech="adjective",
        example="Kauppa on oikealla puolella katua.",
        related_unit_ids=["vocab-vasen", "phrase-missa-asema-on"],
    ),
    VocabularyUnit(
        id="vocab-kokous",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="kokous",
        english="meeting",
        part_of_speech="noun",
        example="Kokous alkaa heti lounaan jalkeen.",
        related_unit_ids=[
            "vocab-sahkoposti",
            "grammar-object-cases",
            "phrase-voinko-siirtaa-kokousta",
        ],
    ),
    VocabularyUnit(
        id="vocab-sahkoposti",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="sahkoposti",
        english="email",
        part_of_speech="noun",
        example="Lahetin sahkopostin opettajalle aamulla.",
        related_unit_ids=["vocab-kokous", "phrase-lahetin-sahkopostin"],
    ),
    VocabularyUnit(
        id="vocab-vuoro",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="vuoro",
        english="shift",
        part_of_speech="noun",
        example="Minulla on iltavuoro tanaan kello neljasta alkaen.",
        related_unit_ids=["vocab-tyo", "phrase-minulla-on-iltavuoro"],
    ),
]

GRAMMAR_UNITS = [
    GrammarUnit(
        id="grammar-verb-present",
        level="A1",
        module_ids=["module-daily-life-routines"],
        title="Present tense verb basics",
        rule="Use the present tense to describe routines, habits, and current actions.",
        example="Asun Tampereella ja opiskelen suomea.",
        related_unit_ids=["vocab-asua", "vocab-opiskella", "phrase-asun-helsingissa"],
    ),
    GrammarUnit(
        id="grammar-time-adverbs",
        level="A1",
        module_ids=["module-daily-life-routines"],
        title="Time adverbs",
        rule="Time words such as aamulla, illalla, tanaan, and huomenna anchor everyday actions.",
        example="Heraan aamulla aikaisin ja lepaan illalla kotona.",
        related_unit_ids=["vocab-aamu", "vocab-ilta", "phrase-heraan-aamulla"],
    ),
    GrammarUnit(
        id="grammar-local-cases",
        level="A2",
        module_ids=["module-moving-around-services"],
        title="Local cases for place and direction",
        rule="Use missa, mihin, and mista patterns to describe where something is and where someone goes.",
        example="Kirjasto on aseman lahella ja menen kirjastoon bussilla.",
        related_unit_ids=[
            "vocab-asema",
            "vocab-kirjasto",
            "phrase-missa-asema-on",
            "phrase-kirjasto-on-lahella",
        ],
    ),
    GrammarUnit(
        id="grammar-question-forms",
        level="A2",
        module_ids=["module-moving-around-services"],
        title="Question forms",
        rule="Questions often use question words such as missa, milloin, and mita, or the -ko suffix.",
        example="Missa asema on ja voinko ostaa lipun taalta?",
        related_unit_ids=["vocab-kirjasto", "phrase-missa-asema-on"],
    ),
    GrammarUnit(
        id="grammar-object-cases",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        title="Object case choice",
        rule="Object form changes depending on whether the action is complete, ongoing, or negative.",
        example="Lahetin sahkopostin mutta en siirtanyt kokousta.",
        related_unit_ids=[
            "vocab-kokous",
            "vocab-sahkoposti",
            "phrase-voinko-siirtaa-kokousta",
            "phrase-lahetin-sahkopostin",
        ],
    ),
    GrammarUnit(
        id="grammar-conjunctions",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        title="Conjunctions in longer answers",
        rule="Use koska, mutta, joten, and vaikka to connect reasons, contrasts, and outcomes.",
        example="Opiskelen iltaisin, koska paivalla olen toissa.",
        related_unit_ids=["vocab-opiskella", "vocab-tyo", "phrase-minulla-on-iltavuoro"],
    ),
]

PHRASE_UNITS = [
    PhraseUnit(
        id="phrase-heraan-aamulla",
        level="A1",
        module_ids=["module-daily-life-routines"],
        finnish="Heraan aamulla kello kuusi.",
        english="I wake up at six in the morning.",
        usage="Use when describing daily rhythm and simple routine answers.",
        related_unit_ids=["vocab-aamu", "grammar-time-adverbs"],
    ),
    PhraseUnit(
        id="phrase-asun-helsingissa",
        level="A1",
        module_ids=["module-daily-life-routines"],
        finnish="Asun Helsingissa ja kayn toissa keskustassa.",
        english="I live in Helsinki and work in the city center.",
        usage="Use when combining place, residence, and work in one answer.",
        related_unit_ids=["vocab-asua", "grammar-verb-present", "vocab-tyo"],
    ),
    PhraseUnit(
        id="phrase-missa-asema-on",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="Anteeksi, missa asema on?",
        english="Excuse me, where is the station?",
        usage="Use when asking for directions politely in public spaces.",
        related_unit_ids=[
            "vocab-asema",
            "vocab-vasen",
            "vocab-oikea",
            "grammar-local-cases",
            "grammar-question-forms",
        ],
    ),
    PhraseUnit(
        id="phrase-kirjasto-on-lahella",
        level="A2",
        module_ids=["module-moving-around-services"],
        finnish="Kirjasto on lahella, ihan aseman vieressa.",
        english="The library is nearby, right next to the station.",
        usage="Use when explaining location clearly with local reference points.",
        related_unit_ids=["vocab-kirjasto", "vocab-asema", "grammar-local-cases"],
    ),
    PhraseUnit(
        id="phrase-voinko-siirtaa-kokousta",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="Voinko siirtaa kokousta huomiseen?",
        english="Can I move the meeting to tomorrow?",
        usage="Use when negotiating schedules at work or in studies.",
        related_unit_ids=["vocab-kokous", "grammar-object-cases", "vocab-tyo"],
    ),
    PhraseUnit(
        id="phrase-lahetin-sahkopostin",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="Lahetin sahkopostin opettajalle aamulla.",
        english="I sent an email to the teacher in the morning.",
        usage="Use when reporting a completed communication task.",
        related_unit_ids=["vocab-sahkoposti", "grammar-object-cases", "vocab-aamu"],
    ),
    PhraseUnit(
        id="phrase-minulla-on-iltavuoro",
        level="B1",
        module_ids=["module-work-and-study-communication"],
        finnish="Minulla on iltavuoro, joten en ehdi kokoukseen.",
        english="I have an evening shift, so I cannot make the meeting.",
        usage="Use when explaining availability and giving a reason.",
        related_unit_ids=["vocab-vuoro", "vocab-ilta", "grammar-conjunctions", "vocab-kokous"],
    ),
]

LEARNING_MODULES = [
    LearningModule(
        id="module-daily-life-routines",
        title="Daily Life and Routines",
        description="Core Finnish for describing home life, daily schedules, and basic personal information.",
        level="A1",
        focus_tags=["content", "relevance"],
        unit_ids=[
            "vocab-aamu",
            "vocab-ilta",
            "vocab-tyo",
            "vocab-asua",
            "vocab-opiskella",
            "grammar-verb-present",
            "grammar-time-adverbs",
            "phrase-heraan-aamulla",
            "phrase-asun-helsingissa",
        ],
    ),
    LearningModule(
        id="module-moving-around-services",
        title="Moving Around and Public Services",
        description="Finnish for asking directions, understanding places, and speaking clearly in service situations.",
        level="A2",
        focus_tags=["clarity", "relevance"],
        unit_ids=[
            "vocab-asema",
            "vocab-kirjasto",
            "vocab-vasen",
            "vocab-oikea",
            "grammar-local-cases",
            "grammar-question-forms",
            "phrase-missa-asema-on",
            "phrase-kirjasto-on-lahella",
        ],
    ),
    LearningModule(
        id="module-work-and-study-communication",
        title="Work and Study Communication",
        description="Structured Finnish for schedule changes, short explanations, and practical communication at work or school.",
        level="B1",
        focus_tags=["clarity", "language_accuracy", "fluency"],
        unit_ids=[
            "vocab-tyo",
            "vocab-opiskella",
            "vocab-kokous",
            "vocab-sahkoposti",
            "vocab-vuoro",
            "grammar-object-cases",
            "grammar-conjunctions",
            "phrase-voinko-siirtaa-kokousta",
            "phrase-lahetin-sahkopostin",
            "phrase-minulla-on-iltavuoro",
        ],
    ),
]
